### PR TITLE
Docusaurus setup complete

### PR DESCRIPTION
**Pull request by hitohata**
## Overview of Implementation

Added Docusaurus setting under the docs directory.

### CODE REVIEW

**Comment by akiomatic** [comment]
Thank you so much!

**Review by akiomatic — APPROVED** [review]
Thank you for your hard work!
Screenshot 2024-02-01 at 17 17 40

**Review by HrRn — APPROVED** [review]
Thank you very much. That was quick!

**Review by Akikaze1119 — APPROVED** [review]
Thank you so much!!

**Review by KaiKoide — APPROVED** [review]
Thank you 👍

**Pull request merged**
