### PR TITLE
docs: add Task with its description and constraints

### PR DESCRIPTION
**Pull request by yuki-92c**
## Changes

- I added  descriptions and constraints of `Task`

> ### Task
> 
> A specific work or activity that tenants are responsible for performing.
> 
> ### taskId (Identifier)
> 
> The TaskId is a UUID
> 
> ### title
> 
> The title is a name of the task
> 
> Constraints:
> 
> - at least 1 character
> - less than 20 characters
> - can be modified at any time
> - must be contained in a `Category`
> 
> ### description
> 
> The `Landlord` can provide details for a task.
> 
> Constraints:
> 
> - at least 10 characters
> - less than 1000 characters
> - can be modified at any time
> - can use bold, italic, and a bulleted or numbered list

## Assignee Checklist:

- [x] The base branch is correct (no accidental merges)

## Reviewer Checklist

- Code readability and simplicity
- Follows best practices and coding standards
- Understandable and maintainable code

### CODE REVIEW

**Comment by akiomatic** [comment]
Could you revise the PR title as it does not follow our standard?
@yuki-92c

**Review by akiomatic — CHANGES_REQUESTED** [review]
Thank you for making changes, but could you revise the PR title as it does not follow our standard?

**Comment by yuki-92c** [comment]
> Thank you for making changes, but could you revise the PR title as it does not follow our standard?

thanks for the comment! edited the title.

**Review by KaiKoide — APPROVED** [review]
LGTM 👍

**Review by Akikaze1119 — APPROVED** [review]
Thank you! LGTM👍

**Review by HrRn — APPROVED** [review]
Thank you!

**Review by akiomatic — APPROVED** [review]
Thank you for fixing the PR title:)

**Pull request merged**
