### PR TITLE
docs: add ER diagram

### LINKED ISSUE #37: Create ER diagram
## Description
This issue is to create an entity relationship diagram based on #10 .
## Features

- [ ] Add ER diagram
- [ ] Use [mermaid.js](https://mermaid.js.org/) to illustrate it

### PR DESCRIPTION
**Pull request by akiomatic**
## Overview
I have added an ER diagram.

## Changes

- Added `er-diagram.md` under `docs/docs`
- Added it to the Docusaurus's sidebar

## Review points
Whether the relations between tables are correct.

## Notes

I'll add a database definition later.

## Assignee Checklist:

- [ ] The base branch is correct (no accidental merges)

## Reviewer Checklist

- Code readability and simplicity
- Follows best practices and coding standards
- Understandable and maintainable code

### CODE REVIEW

**Review by HrRn — APPROVED** [review]
LGTM!

**Review by Akikaze1119 — APPROVED** [review]
LGTM! Thank you ;)

**Review by KaiKoide — APPROVED** [review]
LGTM 👍

**Review by yuki-92c — APPROVED** [review]
LGTM! Thank you:)

**Pull request merged**
